[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "braque"
version = "1.0.1"
authors = [
  { name="Lorenzo Dall'Olio", email="lorenzo.dallolio4@unibo.it" },
]
description = "A small example package"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: GNU License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/LorenzoDallOlio/BRAQUE"
"Bug Tracker" = "https://github.com/LorenzoDallOlio/BRAQUE/issues"
